// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwXTnlNK9E-ELG6R2T16nTs6HB_11tws8',
    appId: '1:967394383529:web:3589fcc9b3191171c43bb8',
    messagingSenderId: '967394383529',
    projectId: 'hausmeisterapp-ccc2d',
    authDomain: 'hausmeisterapp-ccc2d.firebaseapp.com',
    storageBucket: 'hausmeisterapp-ccc2d.appspot.com',
    measurementId: 'G-KG7QSQ6QXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6ab9UHNKkD0I5ckpj31g5_wjY4okz8A',
    appId: '1:967394383529:android:28e31239bae5e88cc43bb8',
    messagingSenderId: '967394383529',
    projectId: 'hausmeisterapp-ccc2d',
    storageBucket: 'hausmeisterapp-ccc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVRvQfedI9Ss488wfiYcQj4z_UL86IpY',
    appId: '1:967394383529:ios:e0b8b6f03fb70bd2c43bb8',
    messagingSenderId: '967394383529',
    projectId: 'hausmeisterapp-ccc2d',
    storageBucket: 'hausmeisterapp-ccc2d.appspot.com',
    iosClientId: '967394383529-6c3ujhirjirsfjkcpq2sj7aiaqs87m83.apps.googleusercontent.com',
    iosBundleId: 'de.gs-giebert.meinDigitalerHausmeister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVRvQfedI9Ss488wfiYcQj4z_UL86IpY',
    appId: '1:967394383529:ios:e0b8b6f03fb70bd2c43bb8',
    messagingSenderId: '967394383529',
    projectId: 'hausmeisterapp-ccc2d',
    storageBucket: 'hausmeisterapp-ccc2d.appspot.com',
    iosClientId: '967394383529-6c3ujhirjirsfjkcpq2sj7aiaqs87m83.apps.googleusercontent.com',
    iosBundleId: 'de.gs-giebert.meinDigitalerHausmeister',
  );
}
